# Generated by Django 4.0.3 on 2022-04-30 10:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in one of these formats: '09xxxxxxxxx', '989xxxxxxxxx', '+989xxxxxxxxx', '+9809xxxxxxxxx', '00989xxxxxxxxx','0989xxxxxxxxx', '009809xxxxxxxxx'. Up to 15 digits allowed.", regex='^(?:0|98|\\+98|\\+980|0098|098|00980)?(9\\d{9})$')]),
        ),
    ]
