# Generated by Django 4.0.3 on 2022-05-01 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_product_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='creator',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
