# Generated by Django 3.2.4 on 2022-05-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_market', '0002_comment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('v', 'Validated'), ('w', 'Waiting to validate by Admin'), ('r', 'Rejected by Admin')], default='w', max_length=1),
        ),
    ]
