# Generated by Django 4.0.3 on 2022-05-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_market', '0006_alter_shoporder_track_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoporder',
            name='status',
            field=models.CharField(choices=[('r', 'Registered order'), ('v', 'Verified by admin'), ('s', 'Sent'), ('d', 'Delivered')], default='r', max_length=1),
        ),
    ]
